name: "books"

services:
  postgres:
    container_name: books_db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_db
    ports:
      - "5432:5432"
    networks:
      - books_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:

networks:
  books_network:
    driver: bridge
